### get user by id
GET http://localhost:3000/auth/2

### get a user by email
GET http://localhost:3000/auth?email=pepito@pepe.io

### Who I Am
GET http://localhost:3000/auth/whoami

### SignUp 
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "pepeto@pepe.io",
  "password": "qwerty"
}

### SignIn
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "pepeto@pepe.io",
  "password": "qwerty"
}

### SignOut
POST http://localhost:3000/auth/signout
Content-Type: application/json

{

}

### update a user
PATCH http://localhost:3000/auth/2
Content-Type: application/json  

{
  "email": "qwerty@asdf.com"
}